def abbreviate(string)
  case string.titleize
  when "Alabama"
    return "AL"	
  when "Montana"	      
    return "MT"
  when "Alaska"	        
    return "AK"
  when "Nebraska"	      
    return "NE"
  when "Arizona"	      
    return "AZ"
  when "Nevada"	        
    return "NV"
  when "Arkansas"	      
    return "AR"
  when "New Hampshire"	
    return "NH"
  when "California"	    
    return "CA"
  when "New Jersey"	    
    return "NJ"
  when "Colorado"	      
    return "CO"
  when "New Mexico"	    
    return "NM"
  when "Connecticut"	  
    return "CT"
  when "New York"	      
    return "NY"
  when "Delaware"	      
    return "DE"
  when "North Carolina"	
    return "NC"
  when "Florida"	      
    return "FL"
  when "North Dakota"	  
    return "ND"
  when "Georgia"	      
    return "GA"
  when "Ohio"	          
    return "OH"
  when "Hawaii"	        
    return "HI"
  when "Oklahoma"	      
    return "OK"
  when "Idaho"	        
    return "ID"
  when "Oregon"	        
    return "OR"
  when "Illinois"	      
    return "IL"
  when "Pennsylvania"	  
    return "PA"
  when "Indiana"	      
    return "IN"
  when "Rhode Island"	  
    return "RI"
  when "Iowa"	          
    return "IA"
  when "South Carolina"	
    return "SC"
  when "Kansas"	        
    return "KS"
  when "South Dakota"	  
    return "SD"
  when "Kentucky"	      
    return "KY"
  when "Tennessee"	    
    return "TN"
  when "Louisiana"	    
    return "LA"
  when "Texas"	        
    return "TX"
  when "Maine"	        
    return "ME"
  when "Utah"	          
    return "UT"
  when "Maryland"	      
    return "MD"
  when "Vermont"	      
    return "VT"
  when "Massachusetts"	
    return "MA"
  when "Virginia"	      
    return "VA"
  when "Michigan"	      
    return "MI"
  when "Washington"	    
    return "WA"
  when "Minnesota"	    
    return "MN"
  when "West Virginia"	
    return "WV"
  when "Mississippi"	  
    return "MS"
  when "Wisconsin"	    
    return "WI"
  when "Missouri"	      
    return "MO"
  when "Wyoming"	      
    return "WY"
  end
end
